# Bienvenue dans Jekyll !
#
# Ce fichier de configuration est destiné aux paramètres qui affectent tout votre site,
# des valeurs que vous êtes censé définir une seule fois et rarement modifier par la suite.
# Si vous vous surprenez à éditer ce fichier très souvent, envisagez d'utiliser les fichiers de données Jekyll
# pour les informations que vous devez mettre à jour fréquemment.
#
# Pour des raisons techniques, ce fichier *n'est PAS* rechargé automatiquement lorsque vous utilisez
# 'bundle exec jekyll serve'. Si vous modifiez ce fichier, veuillez redémarrer le serveur.
#
# Si vous avez besoin d'aide pour la syntaxe YAML, voici quelques références rapides :
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Paramètres du site
# Ils sont utilisés pour personnaliser votre site. Si vous regardez dans les fichiers HTML,
# vous les verrez accessibles via {{ site.title }}, {{ site.email }}, etc.
# Vous pouvez créer n'importe quelle variable personnalisée, accessible via {{ site.ma_variable }}.

title: Bluelink Scriptable
email: bleeband@gmail.com
description: >- # ignore les retours à la ligne jusqu'à "baseurl:"
  Une application Scriptable pour IOS qui vous permet de contrôler votre voiture Hyundai / Kia E-GMP
  via l'API Bluelink. Considérez-la comme une application compagnon à l'app officielle Bluelink,
  avec une interface plus moderne, plus réactive et des fonctionnalités étendues comme les Widgets et le support Siri.
github_username: andyfase

domain: bluelink.andyfase.com       # Si vous souhaitez forcer HTTPS, spécifiez le domaine sans "http", ex. example.com
url: https://bluelink.andyfase.com  # Nom de domaine et protocole de base pour votre site, ex. http://example.com
#baseurl: "/docs"      # mettre le nom du dossier si le site est servi depuis un sous-dossier

# Paramètres de construction
remote_theme: just-the-docs/just-the-docs
# remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-default-layout
  # - jekyll-remote-theme

# Exclusion du traitement
# Les éléments listés ici ne seront pas traités par défaut.
# Tout élément listé sous la clé `exclude:` sera automatiquement ajouté
# à la "liste par défaut" interne.
#
# Les éléments exclus peuvent être traités en les listant explicitement
# dans la section `include:`.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

callouts:
  warning:
    title: Avertissement
    color: red
  info:
    title: Info
    color: blue
